name = "ai-agent-app"
main = "src/index.ts"
compatibility_date = "2024-10-01"

[ai]
binding = "AI"

[durable_objects]
bindings = [
  { name = "CONVERSATION_STATE", class_name = "ConversationState" }
]

[[durable_objects.migrations]]
tag = "v1"
new_classes = ["ConversationState"]

[[workflows]]
name = "conversation-workflow"
binding = "CONVERSATION_WORKFLOW"
class_name = "ConversationWorkflow"

[[workflows]]
name = "conversation-analysis-workflow"
binding = "CONVERSATION_ANALYSIS_WORKFLOW"
class_name = "ConversationAnalysisWorkflow"

[env.production]
compatibility_date = "2024-10-01"

[env.development]
compatibility_date = "2024-10-01"